 name = "dermaclinicsnearme"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

# .nvmrc controls the Node version; no NODE_VERSION set here.
